language: php

services: []

before_script:
  - sudo apt-get update
  - sudo apt-get install -y gpac
  - composer install --dev --prefer-source

php:
  - 7.0
  - 7.1
  - 7.2

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpunit -c phpunit-functional.xml.dist
